trigger:
- master

stages:
- stage: build
  displayName: 'Build and test the website'
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build
      displayName: 'First step in building the website skeleton'

- stage: build_integration
  displayName: 'Build the integration environment'
  dependsOn: build
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'First step in building the integration infrastructure'
      vmImage: 'Ubuntu-16.04'

- stage: deploy_to_integration
  displayName: 'Deploy the website to the integration environment'
  dependsOn: build_integration
  jobs:
  - job: deploy_artefacts_to_integration
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Integration
      displayName: 'First step in deploying the website to integration'

- stage: run_system_quality_tests
  displayName: 'Run the system quality tests'
  dependsOn: deploy_to_integration
  jobs:
  - job: run_non_functional_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Run system quality tests
      displayName: 'Running the system quality tests'

- stage: build_test
  displayName: 'Build the test environment'
  dependsOn: deploy_to_integration
  jobs:
  - job: create_infrastructure
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build Test Infrastructure
      displayName: 'First step in building the test infrastructure'

- stage: deploy_to_test
  displayName: 'Deploy the website to the test environment'
  dependsOn: build_test
  jobs:
  - job: deploy_artefacts_to_test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Test
      displayName: 'First step in deploying the website to test'

- stage: build_demo
  displayName: 'Build the demo environment'
  dependsOn: deploy_to_test
  jobs:
  - job: create_infrastructure
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build Demo Infrastructure
      displayName: 'First step in building the demo infrastructure'

- stage: deploy_to_demo
  displayName: 'Deploy the website to the demo environment'
  dependsOn: build_demo
  jobs:
  - job: deploy_artefacts_to_demo
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Demo
      displayName: 'First step in deploying the website to demo'


      
